### ISSUE TITLE
Emacs look and feel on screenshot

### ISSUE THREAD

**Issue by galderz** [jonathanchu/atom-one-dark-theme#12]
I had a question about the Emacs [screenshot](https://camo.githubusercontent.com/e6565f770c800f41f2b60cc3c06079a39b11e169/687474703a2f2f692e696d6775722e636f6d2f71446e6c4559632e706e67) in the readme file.

How did you achieve the look and feel of Emacs on OSX?

**Comment by galderz** [comment]
To be more precise, I'm not talking about the theme colours themselves, but the way the number lines appear and the mode at the bottom seems quite flat/modern look and feel. Also, what font are you using?

**Comment by jonathanchu** [comment]
Hi @galderz!  Surely, let's see if I can remember this correctly as my config has changed slightly since then...
- Line numbers - I used linum mode.  I removed it a while back from my config, but you can see the diff [here](https://github.com/jonathanchu/dotemacs/commit/6fed01262ff14301fb8035c654fe3d12dcc20258) on how I implemented it
- Mode line - I'm pretty sure I was using @malabarba's excellent [smart-mode-line](https://github.com/Malabarba/smart-mode-line) at this time.  My config [looks like this](https://github.com/jonathanchu/dotemacs/blob/master/emacs-init.org#smart-mode-line).
- Font is Inconsolata.

It's also important to note that I'm using Emacs.app (GUI) on OS X in that screenshot.

Cheers! :beers:

**Comment by Malabarba** [comment]
FWIW, that mode-line is definite smart-mode-line ;-)

**Comment by jonathanchu** [comment]
Thanks @Malabarba!  I couldn't remember for sure what I was using at the time of that screenshot.  :)

There ya go @galderz, straight from the horses mouth! 🐴

**Comment by galderz** [comment]
Hmmmm, I'm still not getting the same as you. To be more precise, I'm using the plain emacs with cocoa distribution for OSX (`brew install --with-cocoa emacs`) and the UI doesn't feel that smooth/flat. Mine feels more blocky. Are you using emacs plus, spacemacs or some other base distribution?

**Comment by jhacksworth** [comment]
Hi @galderz,

Can you post a screenshot?

Here's what my setup looks like:

![emacs](https://user-images.githubusercontent.com/286057/39589211-8e45fb68-4ecb-11e8-88c3-683a5d9bec88.png)

I'm using emacs-plus from homebrew. Note that the mode line in the screenshot is a separate config from the theme.
